### ISSUE TITLE
0.3.3 keeps asking for path maps

### ISSUE THREAD

**Issue by franksl** [gwomacks/php-debug#285]
Hello,
I upgraded to 0.3.3 but each time I run a debug it asks me to specify pah maps, no matter if I click on save each time.
How should this options be specified to prevent the popup?
Thanks,
Frank

**Comment by cchamplin** [comment]
I would suggest trying to remove all of the PHP-Debug settings from config.cson and trying again, it's possible the setting got corrupted resulting in it prompting every time. Let me know.

**Comment by franksl** [comment]
I just tried but had no luck, I'm using a test webserver on localhost, I didn't have to specify any mappings on previous versions.

**Comment by gregCleanSimpleDev** [comment]
Having the same issue, is would be handy if there was a way to disable the `Pathmaps are now configured for each project folder during connection` feature

**Comment by franksl** [comment]
I tested v0.3.4 and these are the results:
- when opening the first php script (ie index.php) it asks for pathMaps, I set the php application directory for both remote and local paths
- if I stay in the index.php file debugging seems working but many console and debugger tabs are open and closed for each request
- whne I open another script it asks for apthMaps again by proposing my home directory as remotePaths (that is not where the scripts reside)

This is my configuration actually ("/var/www/html/dev" is where index.php resides):
```
 "php-debug":
    MaxData: 4096
    ServerPort: 9001
    currentPanelMode: "bottom"
    noPackageInstallPrompt: [
      "ide-php"
      "atom-ide-ui"
    ]
    server:
      serverPort: 9001
    showWelcome: false
    xdebug:
      maxData: 4096
      pathMaps: "[{\"remotePath\":\"/var/www/html/dev\",\"localPath\":\"/var/www/html/dev\"}]"

```
